const addDays = (days, base = new Date()) => {
  const next = new Date(base);
  next.setDate(next.getDate() + days);
  return next;
};

const isoDate = (date) => new Date(date).toISOString().slice(0, 10);

export const demoEvents = [
  {
    _id: "demo-event-1",
    title: "Freshers Welcome Orientation",
    description: "Welcome session for new students with clubs, support services, and campus essentials.",
    date: isoDate(addDays(1)),
    endDate: isoDate(addDays(1)),
    venue: "Open Amphitheatre",
    category: "General",
    mode: "offline",
    status: "upcoming",
    featured: true,
    approvalRequired: false,
    capacity: 1000,
    waitlistCapacity: 100,
    organizerName: "Student Council",
    tags: ["orientation", "students", "campus life"],
    views: 324,
    registeredCount: 412,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-2",
    title: "React UI Workshop",
    description: "Hands-on workshop covering reusable components, responsive layouts, and modern frontend patterns.",
    date: isoDate(addDays(2)),
    endDate: isoDate(addDays(2)),
    venue: "Computer Lab 3",
    category: "Workshop",
    mode: "offline",
    status: "published",
    featured: false,
    approvalRequired: false,
    capacity: 60,
    waitlistCapacity: 20,
    organizerName: "Web Dev Club",
    tags: ["react", "frontend", "workshop"],
    views: 208,
    registeredCount: 41,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-3",
    title: "Resume & Interview Bootcamp",
    description: "Placement prep with resume reviews, mock interviews, and recruiter tips.",
    date: isoDate(addDays(4)),
    endDate: isoDate(addDays(4)),
    venue: "Seminar Hall B",
    category: "Placement",
    mode: "online",
    status: "live",
    featured: true,
    approvalRequired: false,
    capacity: 150,
    waitlistCapacity: 0,
    organizerName: "Training & Placement Cell",
    tags: ["career", "resume", "interview"],
    views: 501,
    registeredCount: 126,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-4",
    title: "Campus Hackathon 2026",
    description: "A 24-hour build sprint for developers, designers, and problem solvers with mentor support.",
    date: isoDate(addDays(7)),
    endDate: isoDate(addDays(8)),
    venue: "Innovation Lab",
    category: "Hackathon",
    mode: "hybrid",
    status: "upcoming",
    featured: true,
    approvalRequired: true,
    capacity: 220,
    waitlistCapacity: 60,
    organizerName: "Coding Club",
    tags: ["ai", "startup", "teamwork"],
    views: 612,
    registeredCount: 180,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-5",
    title: "Industry Connect Panel",
    description: "A dialogue with recruiters and alumni on hiring trends, portfolios, and careers.",
    date: isoDate(addDays(10)),
    endDate: isoDate(addDays(10)),
    venue: "Virtual Townhall",
    category: "Placement",
    mode: "online",
    status: "published",
    featured: false,
    approvalRequired: true,
    capacity: 300,
    waitlistCapacity: 0,
    organizerName: "Placement Cell",
    tags: ["industry", "jobs", "alumni"],
    views: 275,
    registeredCount: 92,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-6",
    title: "Rhythm & Roots Fest",
    description: "A cultural evening with music, dance, and stage performances from across campus.",
    date: isoDate(addDays(12)),
    endDate: isoDate(addDays(12)),
    venue: "Main Auditorium",
    category: "Cultural",
    mode: "offline",
    status: "upcoming",
    featured: true,
    approvalRequired: false,
    capacity: 600,
    waitlistCapacity: 0,
    organizerName: "Cultural Committee",
    tags: ["dance", "music", "festival"],
    views: 430,
    registeredCount: 250,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-7",
    title: "Data Science Masterclass",
    description: "A seminar on practical analytics, dashboards, and modern machine learning workflows.",
    date: isoDate(addDays(15)),
    endDate: isoDate(addDays(15)),
    venue: "Lecture Hall 2",
    category: "Seminar",
    mode: "hybrid",
    status: "completed",
    featured: false,
    approvalRequired: true,
    capacity: 120,
    waitlistCapacity: 30,
    organizerName: "IT Department",
    speakerName: "Guest Faculty",
    speakerRole: "Researcher",
    tags: ["data", "analytics", "ml"],
    views: 145,
    registeredCount: 120,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "demo-event-8",
    title: "Sports Championship Day",
    description: "Inter-college finals for cricket, football, badminton, and track events.",
    date: isoDate(addDays(18)),
    endDate: isoDate(addDays(18)),
    venue: "Sports Ground",
    category: "Sports",
    mode: "offline",
    status: "upcoming",
    featured: false,
    approvalRequired: false,
    capacity: 800,
    waitlistCapacity: 0,
    organizerName: "Sports Council",
    tags: ["fitness", "championship", "team"],
    views: 390,
    registeredCount: 210,
    createdAt: new Date().toISOString(),
  },
];

export const demoAnnouncements = [
  {
    _id: "demo-announcement-1",
    title: "Portal maintenance tonight",
    message: "A short maintenance window is planned tonight. Existing registrations and notices remain available.",
    audience: "all",
    isPinned: true,
    createdAt: new Date().toISOString(),
    createdBy: { name: "Campus team" },
  },
  {
    _id: "demo-announcement-2",
    title: "Hackathon team signups open",
    message: "Teams for the campus hackathon can now be finalized from the events page.",
    audience: "students",
    isPinned: false,
    createdAt: new Date().toISOString(),
    createdBy: { name: "Coding Club" },
  },
  {
    _id: "demo-announcement-3",
    title: "Placement prep materials published",
    message: "Resume templates, interview checklists, and practice questions are ready in the dashboard.",
    audience: "students",
    isPinned: false,
    createdAt: new Date().toISOString(),
    createdBy: { name: "Placement Cell" },
  },
  {
    _id: "demo-announcement-4",
    title: "Volunteer confirmations updated",
    message: "Volunteer assignments and check-in duties have been refreshed for the next event cycle.",
    audience: "volunteers",
    isPinned: false,
    createdAt: new Date().toISOString(),
    createdBy: { name: "Student Council" },
  },
];

export const demoRegistrations = [
  { _id: "demo-registration-1", event: demoEvents[2], status: "registered", checkedIn: true, createdAt: new Date().toISOString() },
  { _id: "demo-registration-2", event: demoEvents[3], status: "registered", checkedIn: false, createdAt: new Date().toISOString() },
];

export const demoWishlistIds = [demoEvents[0]._id, demoEvents[5]._id];

export function findDemoEvent(id) {
  return demoEvents.find((event) => String(event._id) === String(id)) || null;
}

export function getDemoEventRecommendations() {
  return demoEvents.filter((event) => event.featured).slice(0, 4).map((event) => ({ ...event, reasons: ["Popular in campus demos"] }));
}
